### ISSUE TITLE
Crash with jei

### ISSUE THREAD

**Issue by hakanct** [Fureniku/crafting-station#11]
### Steps to Reproduce the Crash

1. Open the crafting station
2. Search for an item in Jei search bar
3. Try to close gui with ESC button on your keyboard and taa-daa game crashes

The game crashed whilst keypressed event handler
Error: java.lang.NullPointerException: Cannot invoke "net.minecraft.world.Container.m_6643_()" because "container" is null

Text above is crash instance on minecraft launcher.

Suspected Mods: 
	Just Enough Items (jei), Version: 15.18.0.79
		Issue tracker URL: https://github.com/mezz/JustEnoughItems/issues?q=is%3Aissue
		at TRANSFORMER/jei@15.18.0.79/mezz.jei.gui.recipes.RecipesGui.m_7379_(RecipesGui.java:453)

	Crafting Station (craftingstation), Version: 1.20.1-1.2.2
		Issue tracker URL: https://github.com/Tfarcenim/crafting-station/issues
		at TRANSFORMER/craftingstation@1.20.1-1.2.2/tfar.craftingstation.client.CraftingStationScreen.m_7856_(CraftingStationScreen.java:54)

And this one is a part of crash report

### Mod Pack URL (Optional)

https://www.curseforge.com/minecraft/modpacks/all-the-mods-9-to-the-sky

### Mod Pack Version (Optional)

1.1.2

### Extra Notes (Optional)

This crash only happens when i am searching while crafting station gui is open.

### Crash Report

https://gist.github.com/hakancqn/aa9ee373a53788db09bc219b360ff14e

**Comment by ecrasswe** [comment]
I am experiencing the same issue, but with different steps to cause the issue.
### Steps to reproduce
1. Open crafting station
2. View recipe for an item
3. Click on the "+"/"Move items" icon
4. Game saves and closes
```
Time: 2024-09-30 22:09:36
Description: mouseReleased event handler

java.lang.NullPointerException: Cannot invoke "net.minecraft.world.Container.m_6643_()" because "container" is null
```
### Mod Pack URL
https://www.curseforge.com/minecraft/modpacks/all-the-mods-9-to-the-sky

#### Mod Pack Ver
1.1.2

### Suspected Mods
```
Crafting Station (craftingstation), Version: 1.20.1-1.2.2
	Issue tracker URL: https://github.com/Tfarcenim/crafting-station/issues
	at TRANSFORMER/craftingstation@1.20.1-1.2.2/tfar.craftingstation.client.CraftingStationScreen.m_7856_(CraftingStationScreen.java:54)

Just Enough Items (jei), Version: 15.18.0.79
	Issue tracker URL: https://github.com/mezz/JustEnoughItems/issues?q=is%3Aissue
	at TRANSFORMER/jei@15.18.0.79/mezz.jei.gui.recipes.RecipesGui.m_7379_(RecipesGui.java:453)
```
### JEI Issue
https://github.com/mezz/JustEnoughItems/issues/3773
Speculated on their end to be an issue with the crafting station
### Extra Notes
Crash only occurs when using the crafting station, not the vanilla crafting table or the inventory

### Crash Report
https://gist.github.com/ecrasswe/6463f80142aae8ae74e49f3486065ed2
